apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: addons
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 35.0.3
    helm:
      releaseName: prometheus-operator
      skipCrds: true
      parameters:
        - name: grafana.enabled
          value: 'false'
        - name: prometheusOperator.admissionWebhooks.enabled
          value: 'false'
      # values: |-
      #   grafana.enabled=false
      #   prometheusOperator.admissionWebhooks.enabled=false
  destination:
    server: 'https://172.23.0.3:6443'
    namespace: prometheus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: addons
  source:
    chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 35.0.3
    helm:
      releaseName: prometheus-operator
      skipCrds: false
      parameters:
        - name: grafana.enabled
          value: 'false'
        - name: prometheusOperator.admissionWebhooks.enabled
          value: 'false'
      # values: |-
      #   grafana.enabled=false
      #   prometheusOperator.admissionWebhooks.enabled=false
  destination:
    server: 'https://172.23.0.3:6443'
    namespace: prometheus
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - Replace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2