apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: addons
  source:
    chart: grafana-operator
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 2.5.2
    helm:
      releaseName: grafana-operator
  destination:
    server: 'https://172.23.0.3:6443'
    namespace: grafana
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
